### ISSUE TITLE
blank page?

### ISSUE THREAD

**Issue by diomed** [khanduras/grav-theme-cardstack#3]
hi

when I install this theme into grav, instead of displaying posts, I get blank page.
could you tell me more about this error and how to fix it?
![screenshot_11](https://cloud.githubusercontent.com/assets/72777/14107909/ecf40f72-f5ba-11e5-9fa3-5e75070d652d.png)

**Comment by khanduras** [comment]
Hi there,
You'll have to copy in the demo content into your `/user/pages` directory.
